apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-01
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/home/rn/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-02
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/home/rn/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-03
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/home/rn/data2"